git clone https://github.com/isaacs/rimraf.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/petkaantonov/bluebird.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/maxogden/concat-stream.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/sboudrias/Inquirer.js.git
git clone https://github.com/grahamlyons/A.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/Raynos/xtend.git
git clone https://github.com/sindresorhus/get-stdin.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/nodejs/readable-stream.git
git clone https://github.com/chalk/supports-color.git
git clone https://github.com/pillarjs/parseurl.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/jshttp/type-is.git
git clone https://github.com/jshttp/on-finished.git
git clone https://github.com/primus/eventemitter3.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/dominictarr/split.git
git clone https://github.com/Microsoft/TypeScript.git
git clone https://github.com/ramda/ramda.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/stefanpenner/es6-promise.git
git clone https://github.com/visionmedia/bytes.js.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/ben-eb/cssnano.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/babel/babylon.git
git clone https://github.com/bestiejs/punycode.js.git
git clone https://github.com/evcohen/eslint-plugin-jsx-a11y.git
git clone https://github.com/bitinn/node-fetch.git
git clone https://github.com/reacttraining/react-router.git
git clone https://github.com/tildeio/rsvp.js.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/rvagg/bl.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/sindresorhus/globby.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/necolas/normalize.css.git
git clone https://github.com/stream-utils/raw-body.git
git clone https://github.com/sindresorhus/camelcase.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/sindresorhus/repeating.git
git clone https://github.com/isaacs/node-graceful-fs.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/facebook/react.git
git clone https://github.com/robrich/gulp-if.git
git clone https://github.com/hij1nx/EventEmitter2.git
git clone https://github.com/kpdecker/jsdiff.git
git clone https://github.com/bestiejs/benchmark.js.git
git clone https://github.com/isaacs/once.git
git clone https://github.com/sindresorhus/pify.git
git clone https://github.com/ljharb/qs.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/github/fetch.git
git clone https://github.com/isaacs/node-glob.git
git clone https://github.com/form-data/form-data.git
git clone https://github.com/JedWatson/classnames.git
git clone https://github.com/jakubpawlowicz/clean-css.git
git clone https://github.com/paulmillr/chokidar.git
git clone https://github.com/sindresorhus/path-exists.git
git clone https://github.com/winstonjs/winston.git
EXIT 
